### ISSUE TITLE
Doesnt work on Forge 1.20.1

### ISSUE THREAD

**Issue by marlester-dev** [coredex-source/ForceGL20-1.2x#1]
Still getting the 65543 Error on startup.
Mod version 1.2.0. Forge 1.20.1, Graphics Driver Intel HD Graphics 3000. OS Windows 7 64 bit.

**Comment by coredex-source** [comment]
Can you send me the startup log please

> Still getting the 65543 Error on startup. Mod version 1.2.0. Forge 1.20.1, Graphics Driver Intel HD Graphics 3000. OS Windows 7 64 bit.

**Comment by coredex-source** [comment]
@marlester-dev

**Comment by coredex-source** [comment]
I'll be closing the issue in 2 days if I get no response.

**Comment by marlester-dev** [comment]
I have no log anymore sorry but I think there was like no error from the plugin, it just crashed and i think the plugin didnt even start at the moment?

**Comment by coredex-source** [comment]
That should not be the case, if that was the case then it was probably something else which caused the crash and not the mod.
