### ISSUE TITLE
[1.21.1] Please add support for newer Neoforge versions

### ISSUE THREAD

**Issue by Cixon** [coredex-source/ForceGL20-1.2x#2]
![2024-08-24 17_12_11-Greenshot](https://github.com/user-attachments/assets/a0855cbf-47ce-474c-bae8-a9d5cca7e50a)

**Neoforge:** 21.1.20

**Comment by Cixon** [comment]
Doesn't load on earliest version either which is 21.1.1 via modrinth launcher

**Comment by coredex-source** [comment]
Well this is not really built for NeoForge but now that you want a version which works with NeoForge I'll see what I can do soon.

**Comment by Cixon** [comment]
if u could make it possible, please! my friend has a older pc and wants to play modern MC so you’d be doing everyone a huge favor!

**Comment by coredex-source** [comment]
I can not promise to make it like super soon as I have to lot to work on already but I will start working on it in like 2 days, it might take a while to get it to work on the modloader due to various reasons, I will most definitely release it for Neoforge so dw.

**Comment by Cixon** [comment]
love this! i sincerely appreciate your efforts!

**Comment by coredex-source** [comment]
Update: I did everything that should make it load on NeoForge but I just can't make it load for some reason, I need assistance of someone here .. I will ask the original dev if they can help, if not we'll have to wait for someone who can help.
I will keep trying to make it work but I've already invested like 6 hours in trying to do so. It should have worked fine but it is not for some reason.

**Comment by Cixon** [comment]
If it helps, I found some resources you may or may not have already seen:

Modding API documentation:
https://docs.neoforged.net/

Source-code:
https://github.com/neoforged/NeoForge

**Comment by coredex-source** [comment]
Thanks for looking them up but I've already implemented the neoforge branch using the above docs.

**Comment by coredex-source** [comment]
Update: The mod is now recognized by the mod loader but crashes while loading, working on a fix for that.

> If it helps, I found some resources you may or may not have already seen:
> 
> Modding API documentation: https://docs.neoforged.net/
> 
> Source-code: https://github.com/neoforged/NeoForge

**Comment by coredex-source** [comment]
And we are done ! It works ! The only thing you need to do after the first launch(which will crash) is to change the fml.toml file located in .minecraft/confg folder and set earlyWindowControl to false which will then look like 

earlyWindowControl = false


Here is the link to the mod: https://modrinth.com/mod/forcegl2.0-remapped/version/ApSkpff6

**Comment by Cixon** [comment]
oh this is excellent! i cannot wait to try it!

**Comment by Cixon** [comment]
> And we are done ! It works ! The only thing you need to do after the first launch(which will crash) is to change the fml.toml file located in .minecraft/confg folder and set earlyWindowControl to false which will then look like
> 
> earlyWindowControl = false
> 
> Here is the link to the mod: https://modrinth.com/mod/forcegl2.0-remapped/version/ApSkpff6

I believe everything works as expected. I seriously appreciate you!
