### ISSUE TITLE
Game crash with sodium

### ISSUE THREAD

**Issue by Shadow00x7** [coredex-source/ForceGL20-1.2x#7]
When i load the game with just fabric and this mod, the game loads fine, but because my system is so old that it can't go past 4fps without any performance mods, but when installing sodium, it crashes the game. here's a crash report, 
[hs_err_pid2960.log](https://github.com/user-attachments/files/18093222/hs_err_pid2960.log)
The system is running on i3 2310m and Hd3000.

**Comment by Shadow00x7** [comment]
Not sure if that is the crash report, because reports are not being generated under the default "crash-reports" directory. IF you need the log, i can upload it.

**Comment by coredex-source** [comment]
@ShadowMC74260 I'd love a proper minecraft log .. and well try buying minecraft (just a suggestion, may or may not fix the issue), according to the JVM log here.. the java is doing weird shenanigans .. try using java 21 from Oracle https://www.oracle.com/java/technologies/downloads/#java21

**Comment by Shadow00x7** [comment]
Here is the minecraft log
[2024-12-11-5.log](https://github.com/user-attachments/files/18139219/2024-12-11-5.log)
Oh and i also tried on oracle's jdk 21, same result. 

Also i plan on playing the game on xbox game pass once i buy a proper pc. For now, i am here. My friends are planning on doing another run of 2 week minecraft session, so i kinda need to play it.

**Comment by coredex-source** [comment]
This is not a crash related to any of the mods, the crash is definitely related to smth else. Try changing your launcher or smth.

**Comment by coredex-source** [comment]
Try changing your render distance and simulation distance to 6 each aswell

**Comment by Shadow00x7** [comment]
I set the render distance and simulation distance to 6 each, and the world loaded for a good 5 seconds, and unfortunately after that it crashed. Oh and the world wasn't being rendered at all. 

Previously was using a fabolusly optimized modpack, that came with tons of mod and configuration, so this time, i took out a handfull of mods that is related to optimization only, and put it in a new installation, and still does not work

Although the world renders just fine when on vanilla, and removing everything else other than forcegl. But lags a lot to the point of having no difference when using software renderer (dropping opengl32.dll in java installation directory)

After some mod test for a while, i came to this conclusion that the game does not crash and renders perfectly fine when i add any other mods, but does when i add sodium. As i said before, the game crashes even when there's nothing but sodium install. The world loads, but does not render, and after that, the game crashes. I remembered to put render and simulation to 6 each this time too. But no luck.

**Comment by coredex-source** [comment]
@ShadowMC74260 I do not support piracy but try using Legacy Launcher instead of your SKLauncher. The mod is completely compatible with sodium on the exact graphics card you have in your system as my testing laptop has the same specs. I tried launching it with just sodium and forceGL and it works just fine on Legacy launcher - https://llaun.ch/en

**Comment by coredex-source** [comment]
I cannot seem to comprehend why it crashes on your system. If changing the launcher still doesn't work I might provide you with a third party GPU driver which can be kinda tricky to install.

**Comment by coredex-source** [comment]
Also .. remove Mesa 3D [Software renderer]

**Comment by Shadow00x7** [comment]
No luck. Here's a log even though it's the same like previous. 
[tl-logger15769629772930605166.txt](https://github.com/user-attachments/files/18155286/tl-logger15769629772930605166.txt)

So a custom GPU driver? Sure, I am in. 

Also sorry for pirating, as i don't have an access to an credit card cuz i am not over 18 yet, and my parents won't give me theirs either. So yea. I feel guilty for not paying too.

**Comment by coredex-source** [comment]
@ShadowMC74260 Here you go https://www.reddit.com/r/lowendgaming/comments/1258usx/updated_win1011_drivers_for_intel_hd_3000/

**Comment by coredex-source** [comment]
Closing the issue due to no response.

**Comment by Shadow00x7** [comment]
Oh damn, That driver didn't work either. I got frustated in the end and ended up installing ubuntu and play over there until the 2 wek session ended, that's also when i forgot about this and moved on with my life. sry, but thanks for trying to help.

**Comment by coredex-source** [comment]
> Oh damn, That driver didn't work either. I got frustated in the end and ended up installing ubuntu and play over there until the 2 wek session ended, that's also when i forgot about this and moved on with my life. sry, but thanks for trying to help.

Don't worry it's fine. Thank you for taking some time out and replying to this thread.
